name: elementary-os-sdk
version: '0.4'
summary: Library bundle for developers of elementary os applications
description: |
  This prototype snap contains only the necessary libraries required by
  elementary os applications.

confinement: devmode

parts:
  # ppa:
  #   plugin: nil
  #   prepare: |
  #     add-apt-repository -y ppa:elementary-os/stable
  #     add-apt-repository -y ppa:elementary-os/os-patches
  #     echo "Package: *" > /etc/apt/preferences.d/elementary-stable
  #     echo "Pin: release o=LP-PPA-elementary-os-stable" >> /etc/apt/preferences.d/elementary-stable
  #     echo "Pin-Priority: 1000" >> /etc/apt/preferences.d/elementary-stable
  #     echo "Package: *" > /etc/apt/preferences.d/elementary-patches
  #     echo "Pin: release o=LP-PPA-elementary-os-os-patches" >> /etc/apt/preferences.d/elementary-patches
  #     echo "Pin-Priority: 1000" >> /etc/apt/preferences.d/elementary-patches
  #     apt update
  #     apt dist-upgrade -y
  # vala:
  #   plugin: autotools
  #   source: https://github.com/GNOME/vala.git
  #   source-tag: '0.36.5'
  #   build-packages:
  #     - libglib2.0-dev
  #     - bison
  #     - valac
  #     - autotools-dev
  #     - flex
  #     - gnome-pkg-tools
  #     - help2man
  #     - xsltproc
  #     - libdbus-1-dev
  #     - dbus
  #     - libgirepository1.0-dev
  gsignond:
    source: https://gitlab.com/accounts-sso/gsignond.git
    plugin: autotools
    source-tag: '1.0.6'
  libgsignon-glib:
    source: https://gitlab.com/accounts-sso/libgsignon-glib.git
    plugin: autotools
    source-tag: '2.4.1'
  granite:
    after: [gee]
    source: https://github.com/elementary/granite.git
    plugin: cmake
    source-tag: '0.4.1'
    build-packages:
      - libgtk-3-dev
      - libglib2.0-dev
  gala:
    after: [plank]
    source: https://github.com/elementary/gala.git
    plugin: autotools
  switchboard:
    after: [granite]
    source: https://github.com/elementary/switchboard.git
    plugin: cmake
    source-tag: '2.3.0'
  wingpanel:
    after: [granite]
    source: https://github.com/elementary/wingpanel.git
    plugin: cmake
    source-tag: '2.0.4'
  plank:
    after: [gee]
    source: https://github.com/ricotz/plank.git
    plugin: autotools
    source-tag: '0.11.3'
#  autoconf-archive:
#    source: http://www.localmsp.org/gnu/autoconf-archive/autoconf-archive-2016.09.16.tar.xz
#    plugin: autotools
  gee: 
    source: git://git.gnome.org/libgee
    source-tag: '0.20.0'
    plugin: autotools
    build-packages:
      - gobject-introspection
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libtool
      - gir1.2-gee-0.8
      - autoconf-archive
      - valac
  
